### ISSUE TITLE
Улучшение плеера

### ISSUE THREAD

**Issue by hachikoharuno** [wheremyfiji/ShikiWatch#15]
Я в основном использую смартфон с заблокированной ориентацией и когда я отрываю плеер, он открывается в вертикальном режиме, что не удобно (на xiaomi появляется кнопка изменения ориентации при повороте, но после обновления приложения она почему-то пропала, хотя я думаю это не важно)

Если исходить в целом из опыта других приложений, то обычно плеер всегда открывается в горизонтальном режиме, так что не думаю, что данное неудобство касается только моего опыта использования.

**Comment by wheremyfiji** [comment]
В след. обновлении подправлю. Чето не думал об этом даже.

> (на xiaomi появляется кнопка изменения ориентации при повороте, но после обновления приложения она почему-то пропала, хотя я думаю это не важно)

Не пропала, просто статус бар вызови или панель навигации.
