### ISSUE TITLE
[windows] Добавить в плеер управление скоростью

### ISSUE THREAD

**Issue by neverlane** [wheremyfiji/ShikiWatch#18]
его почему-то нет)

![image](https://github.com/wheremyfiji/ShikiWatch/assets/63193736/819f52af-db99-4889-8684-2b401035b363)

**Comment by wheremyfiji** [comment]
забыл :trollface:

**Comment by neverlane** [comment]
топ 😊

**Comment by wheremyfiji** [comment]
вернул
