### ISSUE TITLE
Неправильное поведение отметки серий 

### ISSUE THREAD

**Issue by Andryshik345** [wheremyfiji/ShikiWatch#24]
В режиме вида сетка, если долгим нажатием на тайтл открыть панель, то при нажатии на плюс или минус счетчик сбрасывается и кнопки блокируются. Если же зайти на страницу тайтла и открыть панель там, то все нормально.
Запись прикладываю:
https://github.com/wheremyfiji/ShikiWatch/assets/24612088/004e90d1-974b-4c9d-9446-b21e658ce3fc

**Comment by wheremyfiji** [comment]
fixed
