### ISSUE TITLE
Добавить поддержку Chromecast

### ISSUE THREAD

**Issue by Dan-Master** [wheremyfiji/ShikiWatch#26]
Прошу рассмотреть техническую возможность реализовать в приложении функцию стриминга через Chromecast на совместимые устройства: Android TV, сертифицированные Google TV box'ы, etc...

Я думаю многие согласятся, что куда комфортнее смотреть анимешечки на большом экране, при этом не теряя в удобстве управлять воспроизведением с телефона)

![FontAwesome-Brands-Chromecast-icon](https://github.com/user-attachments/assets/30a5d4e0-c23f-4a65-8d81-b35f4b8573e0)

**Comment by wheremyfiji** [comment]
хромкаста не будет.
