### ISSUE TITLE
Разное отображение отметок серии

### ISSUE THREAD

**Issue by Andryshik345** [wheremyfiji/ShikiWatch#27]
В виде "Список" не показывается "кол-во просмотренных серий / кол-во вышедших", как это сделано в виде "Сетка". 
Скриншоты прикладываю:
<details>
<summary>Spoiler warning</summary>

![Screenshot_20240808-094213_ShikiWatch](https://github.com/user-attachments/assets/f8756c9b-bf34-470e-90e4-cff1749a838c)

![Screenshot_20240808-094226_ShikiWatch](https://github.com/user-attachments/assets/362ef7ec-f8aa-42bf-8f02-e8587ab6baaf)

</details>

Не совсем удобно следить за этими двумя цифрами (в первом случае нужно заходить в карточку тайтла).
Также видно, что, например, у тайтла "Башня бога" в одном случае пишет "? серий", а в другом "из 0 серий".

**Comment by wheremyfiji** [comment]
Ну да, чёт не очень получилось. Думаю, что можно сделать чтобы прогресс бар показывал просмотрено / сколько вышло, а насчёт ? и 0 - это на шики нету инфы по эпизодам. Пусть тогда ? будет везде

**Comment by Andryshik345** [comment]
@wheremyfiji прогресс-бар это, конечно, хорошо, но хотелось бы конкретную цифру видеть.
Я могу предложить вот так:
<details>
<summary>spoiler</summary>

![Screenshot_20240808-111155_ShikiWatch](https://github.com/user-attachments/assets/67f1dc09-f0c1-4c4c-8a73-92aabb688c85)

</details>

Или вы так и имели ввиду? :)
